"""
plot_lhs_multiparam.py
=======================
Generates all diagnostic figures for an N-parameter LHS sweep (series 80,
81, 82, or 83). Replaces plot_lhs_5param.py, plot_lhs_6param.py, and
plot_lhs_11param.py, which were three copies of the same script with the
swept-parameter list hardcoded differently in each.

Switch series by editing ACTIVE_SERIES below (one line). Everything else
-- which columns are swept, axis labels, output paths, which optional
deep-dive figures to draw -- is driven by the SERIES_PRESETS dict.

Usage (run from the smf_demo directory):
    python plot_lhs_multiparam.py

Produces up to 11 figures saved to:
    calibration_work/03_comparisons/sensitivity_plots/{SERIES_LABEL}/

Core figure list (all series, figs 1-9 identical structure regardless of N):
    fig1_hydrograph_envelope_all.png   -- All runs: envelope + median + best run
    fig2_hydrograph_envelope_kge0.png  -- KGE > 0 runs only + filtered median
    fig3_correlation_bar.png           -- Pearson r of each swept param vs KGE
    fig4_parallel_coordinates.png      -- All N params as vertical axes, colored by KGE
    fig5_pairwise_scatter.png          -- C(N,2)-panel pairwise scatter matrix, colored by KGE
    fig6_kge_vs_each_param.png         -- N-panel KGE vs each parameter (1D response curves)
    fig7_pbias_vs_kge.png              -- PBIAS vs KGE scatter, colored by Ks multiplier
    fig8_top15_table.png               -- Top-15 runs by KGE as formatted table
    fig9_kge_components_vs_ks.png      -- r / alpha / beta each vs Ks, colored by KGE

Optional per-series deep-dive figures (fig10, fig11, ...) are listed in each
preset's "deep_dives" entry and rendered by one of two reusable templates:
    "single_vs_ks_pbias"   -- (a) KGE vs param, colored by Ks
                              (b) param vs Ks, colored by KGE
                              (c) PBIAS vs param, colored by KGE
    "two_param_interaction" -- (a) KGE vs param1, colored by Ks
                               (b) KGE vs param2, colored by Ks
                               (c) param1 x param2, colored by KGE

======================================================================
UPDATED / CONSOLIDATED -- see notes below
======================================================================
This script was generated by merging three near-duplicate files:
    - plot_lhs_5param.py   (series 80 KsLo / 81 KsHi -- 4 swept params)
    - plot_lhs_6param.py   (series 82 -- adds psiB_mult -- 5 swept params)
    - plot_lhs_11param.py  (series 83 -- adds channelwidthcoeff, thetaS_mult
                             -- 7 swept params)
Figures 1-9 in all three source files were already written generically
over a PARAM_META dict, so consolidating them required only generalizing
the fig5 pairwise-panel-count and fig6 subplot-grid layout to work for any
N, and moving each series' specific parameter list/labels into a
SERIES_PRESETS dict. Figures 10/11 (deep-dives) were bespoke per series;
they are now two reusable template functions instead of copy-pasted
per-series blocks.

No metrics were dropped from THIS script's own logic (it never referenced
peak_error_m3s, volume_error_pct, or rmse_m3s -- those are eliminated
project-wide, see build_sensitivity_run.py / run_sensitivity_single.py
metric notes and plot_recession_residual_pca.py, plot_best_run_diagnostic.py,
and plot_sensitivity.py, which did reference them and were updated
separately).

The old files (plot_lhs_5param.py, plot_lhs_6param.py, plot_lhs_11param.py)
should be deleted/archived once this replacement is verified against a
saved figure set from each series.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.ticker as mticker
from itertools import combinations
from pathlib import Path

# ======================================================================
# SERIES PRESETS -- one entry per historical script this file replaces
# ======================================================================
SERIES_PRESETS = {
    "80": dict(
        results_csv="lhs_results_5param_KsLo.csv",
        series_label="Series80_KsLo",
        series_title_prefix="Series 80",
        run_script="run_lhs_5param.py",
        fixed_note="f fixed at 0.020 mm\u207b\u00b9",
        n_cols_pairwise=3,
        param_meta={
            "Ks_mult":          dict(label="Ks multiplier",                short="Ks x", fmt="{:.2f}x", table_fmt="{:.2f}"),
            "kinemvelcoef":     dict(label="Hillslope velocity coef. cv",   short="cv",   fmt="{:.2f}",  table_fmt="{:.2f}"),
            "flowexp":          dict(label="Hillslope velocity exp. r",    short="r",    fmt="{:.3f}",  table_fmt="{:.3f}"),
            "channelroughness": dict(label="Channel roughness n",          short="n",    fmt="{:.4f}",  table_fmt="{:.4f}"),
        },
        deep_dives=[],
    ),
    "81": dict(
        results_csv="lhs_results_5param_KsHi.csv",
        series_label="Series81_KsHi",
        series_title_prefix="Series 81",
        run_script="run_lhs_5param.py",
        fixed_note="f fixed at 0.020 mm\u207b\u00b9",
        n_cols_pairwise=3,
        param_meta={
            "Ks_mult":          dict(label="Ks multiplier",                short="Ks x", fmt="{:.2f}x", table_fmt="{:.2f}"),
            "kinemvelcoef":     dict(label="Hillslope velocity coef. cv",   short="cv",   fmt="{:.2f}",  table_fmt="{:.2f}"),
            "flowexp":          dict(label="Hillslope velocity exp. r",    short="r",    fmt="{:.3f}",  table_fmt="{:.3f}"),
            "channelroughness": dict(label="Channel roughness n",          short="n",    fmt="{:.4f}",  table_fmt="{:.4f}"),
        },
        deep_dives=[],
    ),
    "82": dict(
        results_csv="lhs_results_6param_82.csv",
        series_label="Series82_6param_psiB",
        series_title_prefix="Series 82",
        run_script="run_lhs_6param.py",
        fixed_note="f fixed at 0.020 mm\u207b\u00b9",
        n_cols_pairwise=4,
        param_meta={
            "Ks_mult":          dict(label="Ks multiplier",                short="Ks x",  fmt="{:.2f}x", table_fmt="{:.2f}"),
            "kinemvelcoef":     dict(label="Hillslope velocity coef. cv",   short="cv",    fmt="{:.2f}",  table_fmt="{:.2f}"),
            "flowexp":          dict(label="Hillslope velocity exp. r",    short="r",     fmt="{:.3f}",  table_fmt="{:.3f}"),
            "channelroughness": dict(label="Channel roughness n",          short="n",     fmt="{:.4f}",  table_fmt="{:.4f}"),
            "psiB_mult":        dict(label="Air-entry pressure PsiB mult", short="psiB x",fmt="{:.3f}x", table_fmt="{:.3f}"),
        },
        deep_dives=[
            dict(kind="single_vs_ks_pbias", col="psiB_mult", label="psiB multiplier",
                 baseline_note="Baseline PsiB per class: RS=\u2212390, CO=\u2212401, CeD=\u2212183, "
                                "EbD=\u2212450, Cb=\u2212117 mm",
                 fig_name="fig10_psib_sensitivity.png",
                 title_tag="psiB_mult sensitivity deep-dive"),
        ],
    ),
    "83": dict(
        results_csv="lhs_results_11param_83.csv",
        series_label="Series83_11param",
        series_title_prefix="Series 83",
        run_script="run_lhs_11param.py",
        fixed_note="f, As, Au fixed",
        n_cols_pairwise=4,
        param_meta={
            "Ks_mult":           dict(label="Ks multiplier",                     short="Ks x",   fmt="{:.2f}x", table_fmt="{:.2f}"),
            "kinemvelcoef":      dict(label="Hillslope velocity coef. cv",        short="cv",     fmt="{:.2f}",  table_fmt="{:.2f}"),
            "flowexp":           dict(label="Hillslope velocity exp. r",         short="r",      fmt="{:.3f}",  table_fmt="{:.3f}"),
            "channelroughness":  dict(label="Channel roughness n",               short="n",      fmt="{:.4f}",  table_fmt="{:.4f}"),
            "channelwidthcoeff": dict(label="Channel width coeff. \u03b1B",       short="\u03b1B",fmt="{:.3f}",  table_fmt="{:.3f}"),
            "thetaS_mult":       dict(label="Saturated moisture \u03b8s mult",    short="\u03b8s x",fmt="{:.3f}x",table_fmt="{:.3f}"),
            "psiB_mult":         dict(label="Air-entry pressure PsiB mult",       short="psiB x", fmt="{:.3f}x", table_fmt="{:.3f}"),
        },
        deep_dives=[
            dict(kind="two_param_interaction",
                 col1="channelwidthcoeff", label1="Channel width coeff. \u03b1B",
                 col2="thetaS_mult",       label2="Saturated moisture \u03b8s multiplier",
                 baseline_note="\u03b1B baseline=2.33 (Ivanov 2004)  |  \u03b8s constrained > \u03b8*s=0.37",
                 fig_name="fig10_new_params_deepdive.png",
                 title_tag="New-parameter deep-dive"),
            dict(kind="single_vs_ks_pbias", col="psiB_mult", label="psiB multiplier",
                 baseline_note="Baseline PsiB per class: RS=\u2212390, CO=\u2212401, CeD=\u2212183, "
                                "EbD=\u2212450, Cb=\u2212117 mm",
                 fig_name="fig11_psib_sensitivity.png",
                 title_tag="psiB_mult sensitivity deep-dive"),
        ],
    ),
}

# ======================================================================
# CONFIG -- edit this one line to switch series
# ======================================================================
ACTIVE_SERIES = "83"
# ======================================================================

if ACTIVE_SERIES not in SERIES_PRESETS:
    raise ValueError(f"ACTIVE_SERIES must be one of {list(SERIES_PRESETS)}, got {ACTIVE_SERIES!r}")

cfg = SERIES_PRESETS[ACTIVE_SERIES]
RESULTS_CSV     = cfg["results_csv"]
SERIES_LABEL    = cfg["series_label"]
PARAM_META_CFG  = cfg["param_meta"]
FIXED_NOTE      = cfg["fixed_note"]
N_COLS_PAIRWISE = cfg["n_cols_pairwise"]
DEEP_DIVES      = cfg["deep_dives"]

EVENT_LABEL      = "SMF Aug 12, 2014"
EVENT_CROP_START = "2014-08-12 17:30"
EVENT_CROP_END   = "2014-08-12 21:00"

# -----------------------------------------------------------------------
# PATHS
# -----------------------------------------------------------------------
script_dir = Path.cwd()
project_root = script_dir.parent if script_dir.name == "smf_demo" else script_dir
calib_dir    = project_root / "calibration_work"
summary_dir  = calib_dir / "03_comparisons" / "summary_tables"
csv_dir      = calib_dir / "03_comparisons" / "csv_exports"
plot_dir     = calib_dir / "03_comparisons" / "sensitivity_plots" / SERIES_LABEL
plot_dir.mkdir(parents=True, exist_ok=True)

# -----------------------------------------------------------------------
# LOAD RESULTS
# -----------------------------------------------------------------------
results_path = summary_dir / RESULTS_CSV
if not results_path.exists():
    raise FileNotFoundError(
        f"LHS results not found: {results_path}\n"
        f"Run {cfg['run_script']} first."
    )

df = pd.read_csv(results_path)
print(f"Loaded {len(df)} LHS runs from {results_path.name}")

PARAM_KEYS = list(PARAM_META_CFG.keys())
required_cols = ["run_id"] + PARAM_KEYS + ["kge", "nse", "pbias_pct", "kge_r", "kge_alpha", "kge_beta"]
missing = [c for c in required_cols if c not in df.columns]
if missing:
    raise ValueError(f"Missing columns in results CSV: {missing}\nAvailable: {list(df.columns)}")

df = df.dropna(subset=required_cols).reset_index(drop=True)
print(f"  {len(df)} runs after dropping NaN rows")

n_params = len(PARAM_KEYS)

ks_lo = df["Ks_mult"].min()
ks_hi = df["Ks_mult"].max()
SERIES_TITLE = f"{cfg['series_title_prefix']}  |  Ks {ks_lo:.1f}-{ks_hi:.1f}x  |  {n_params} free params"

print(f"Series: {SERIES_TITLE}")
print(f"Plots -> {plot_dir}")

# Build PARAM_META with actual data arrays attached (mirrors original scripts)
PARAM_META = {}
for key, meta in PARAM_META_CFG.items():
    PARAM_META[key] = dict(meta, vals=df[key].values)
PARAM_LABELS = [PARAM_META[k]["label"] for k in PARAM_KEYS]

ks_vals    = df["Ks_mult"].values
kge_vals   = df["kge"].values
nse_vals   = df["nse"].values
pbias_vals = df["pbias_pct"].values

best_idx    = int(np.argmax(kge_vals))
best_run_id = df["run_id"].iloc[best_idx]
best_kge    = kge_vals[best_idx]

print(f"\n  Best run: {best_run_id}")
print(f"  Best KGE: {best_kge:.3f}")
print(f"  KGE range:   {kge_vals.min():.3f} to {kge_vals.max():.3f}")
print(f"  PBIAS range: {pbias_vals.min():.1f}% to {pbias_vals.max():.1f}%")

# KGE colormap -- plasma has no white/near-white values on a white background.
# Norm uses 5th-95th percentile of actual data with clip=True so:
#   (a) colour range reflects the real spread of results
#   (b) norm_val is always in [0,1], preventing alpha ValueError
KGE_CMAP = plt.get_cmap("plasma")
kge_p05  = np.percentile(kge_vals, 5)
kge_p95  = np.percentile(kge_vals, 95)
KGE_NORM = mcolors.Normalize(vmin=kge_p05, vmax=kge_p95, clip=True)


def save_fig(fig, filename):
    path = plot_dir / filename
    fig.savefig(path, dpi=150, bbox_inches="tight")
    print(f"  Saved: {path.name}")
    plt.close(fig)


def build_response_curve_axes(fig, n):
    """
    Build an (approximately) centred two-row grid of n subplot axes.
    n<=4  -> simple n_top x n_bot grid (2x2 for n=4, single row otherwise)
    n>4   -> top row = ceil(n/2) axes, bottom row = floor(n/2) axes,
             bottom row horizontally centred under the top row.
    This reproduces the hand-built gridspec layouts used in the original
    5-param (2x2), 6-param (3+2), and 11-param (4+3) scripts for any N.
    """
    if n <= 4:
        rows = 2 if n > 2 else 1
        cols = int(np.ceil(n / rows))
        gs = fig.add_gridspec(rows, cols)
        axes = []
        for i in range(n):
            r, c = divmod(i, cols)
            axes.append(fig.add_subplot(gs[r, c]))
        return axes

    top_n   = -(-n // 2)      # ceil(n/2)
    bot_n   = n - top_n
    n_cols  = 2 * top_n
    gs      = fig.add_gridspec(2, n_cols, hspace=0.4, wspace=0.4)
    axes_top = [fig.add_subplot(gs[0, 2 * i:2 * i + 2]) for i in range(top_n)]
    offset   = top_n - bot_n
    axes_bot = [fig.add_subplot(gs[1, 2 * i + offset:2 * i + offset + 2]) for i in range(bot_n)]
    return axes_top + axes_bot


# -----------------------------------------------------------------------
# LOAD ALL HYDROGRAPH CSVs
# -----------------------------------------------------------------------
def load_all_hydrographs(run_ids):
    hydrographs   = {}
    missing_count = 0
    for run_id in run_ids:
        csv_path = csv_dir / f"{run_id}_compare_obs_sim.csv"
        if csv_path.exists():
            try:
                hdf = pd.read_csv(csv_path, index_col=0, parse_dates=True)
                hydrographs[run_id] = hdf
            except Exception as e:
                print(f"  Warning: could not read {csv_path.name}: {e}")
                missing_count += 1
        else:
            missing_count += 1
    if missing_count:
        print(f"  Warning: {missing_count} hydrograph CSVs not found.")
    print(f"  Loaded {len(hydrographs)} hydrograph CSVs.")
    return hydrographs


print("\nLoading hydrograph CSVs...")
all_hydros = load_all_hydrographs(df["run_id"].values)

obs_series = None
for hdf in all_hydros.values():
    if "Observed" in hdf.columns:
        obs_series = hdf["Observed"]
        break
if obs_series is None:
    print("  WARNING: No observed series found. Hydrograph figures will be skipped.")


# -----------------------------------------------------------------------
# FIGURES 1 & 2: Hydrograph uncertainty envelopes
# -----------------------------------------------------------------------
def plot_hydrograph_envelope(hydros_subset, df_subset, title_suffix, filename,
                              envelope_color, median_color, filter_label):
    if obs_series is None or len(hydros_subset) == 0:
        print(f"  Skipping {filename} -- insufficient data.")
        return

    common_idx = obs_series.index
    sim_matrix = pd.DataFrame(index=common_idx)
    best_run_in_subset = df_subset.loc[df_subset["kge"].idxmax(), "run_id"]

    for run_id, hdf in hydros_subset.items():
        sim_matrix[run_id] = hdf["Simulated"].reindex(common_idx)

    sim_matrix = sim_matrix.dropna(how="all")
    if sim_matrix.empty:
        print(f"  Skipping {filename} -- sim_matrix empty after dropna.")
        return

    sim_matrix  = sim_matrix.loc[EVENT_CROP_START:EVENT_CROP_END]
    obs_cropped = obs_series.reindex(sim_matrix.index)

    p05 = sim_matrix.quantile(0.05, axis=1)
    p25 = sim_matrix.quantile(0.25, axis=1)
    p50 = sim_matrix.quantile(0.50, axis=1)
    p75 = sim_matrix.quantile(0.75, axis=1)
    p95 = sim_matrix.quantile(0.95, axis=1)

    best_sim      = hydros_subset.get(best_run_in_subset)
    n_runs        = len(hydros_subset)
    best_kge_here = df_subset.loc[df_subset["run_id"] == best_run_in_subset, "kge"].values[0]

    fig, ax = plt.subplots(figsize=(12, 6))
    ax.set_facecolor("#f5f5f5")

    for run_id, hdf in hydros_subset.items():
        sim = hdf["Simulated"].reindex(sim_matrix.index)
        ax.plot(sim_matrix.index, sim, color=envelope_color, alpha=0.08,
                linewidth=0.5, zorder=1)

    ax.fill_between(sim_matrix.index, p05, p95,
                    color=envelope_color, alpha=0.25, label="5th-95th percentile", zorder=2)
    ax.fill_between(sim_matrix.index, p25, p75,
                    color=envelope_color, alpha=0.45, label="25th-75th percentile", zorder=3)
    ax.plot(sim_matrix.index, p50, color=median_color, linewidth=1.8,
            label=f"{filter_label} Median", zorder=4)

    if best_sim is not None:
        ax.plot(sim_matrix.index, best_sim["Simulated"].reindex(sim_matrix.index),
                color="crimson", linewidth=1.6, linestyle="--",
                label=f"Best run (KGE={best_kge_here:.3f})", zorder=5)

    ax.plot(sim_matrix.index, obs_cropped,
            color="black", linewidth=2.2, label="Observed", zorder=6)

    ax.set_xlabel("Time", fontsize=11)
    ax.set_ylabel("Discharge (m\u00b3/s)", fontsize=11)
    ax.set_title(
        f"Hydrograph uncertainty -- {title_suffix}  (n={n_runs})\n"
        f"{n_params}-parameter LHS  |  {SERIES_TITLE}  |  {EVENT_LABEL}",
        fontsize=12
    )
    ax.legend(fontsize=9, loc="upper right", facecolor="white", framealpha=0.9)
    ax.xaxis.set_major_formatter(plt.matplotlib.dates.DateFormatter("%H:%M"))
    fig.autofmt_xdate(rotation=0, ha="center")
    fig.tight_layout()
    save_fig(fig, filename)


print("\nFigure 1: Hydrograph envelope -- all runs")
all_hydros_dict = {rid: all_hydros[rid] for rid in df["run_id"].values if rid in all_hydros}
plot_hydrograph_envelope(
    hydros_subset=all_hydros_dict,
    df_subset=df[df["run_id"].isin(all_hydros_dict)].copy(),
    title_suffix="All runs",
    filename="fig1_hydrograph_envelope_all.png",
    envelope_color="#4c8cbf", median_color="#1a5fa8", filter_label="All runs",
)

print("Figure 2: Hydrograph envelope -- KGE > 0 runs only")
df_kge0     = df[df["kge"] > 0].copy()
hydros_kge0 = {rid: all_hydros[rid] for rid in df_kge0["run_id"].values if rid in all_hydros}
plot_hydrograph_envelope(
    hydros_subset=hydros_kge0,
    df_subset=df_kge0,
    title_suffix="KGE > 0 runs",
    filename="fig2_hydrograph_envelope_kge0.png",
    envelope_color="#e8833a", median_color="#b85c00", filter_label="KGE > 0",
)


# -----------------------------------------------------------------------
# FIGURE 3: Pearson correlation bar chart
# -----------------------------------------------------------------------
print("Figure 3: Correlation bar chart")

correlations = {key: np.corrcoef(df[key].values, kge_vals)[0, 1] for key in PARAM_KEYS}

fig, ax = plt.subplots(figsize=(10, 6))
bar_colors = ["#2ecc71" if v >= 0 else "#e74c3c" for v in correlations.values()]
bars = ax.barh(PARAM_LABELS, list(correlations.values()),
               color=bar_colors, edgecolor="white", height=0.55)
ax.axvline(0, color="black", linewidth=0.8)
ax.set_xlabel("Pearson r  (parameter value vs KGE)", fontsize=11)
ax.set_title(
    f"Parameter-KGE correlations -- {n_params}-param LHS  {SERIES_TITLE}  (n={len(df)})\n"
    f"{EVENT_LABEL}  |  Green = higher value \u2192 better KGE  |  Red = opposite",
    fontsize=11
)
for bar, val in zip(bars, correlations.values()):
    x_pos = val + 0.01 if val >= 0 else val - 0.01
    ha    = "left" if val >= 0 else "right"
    ax.text(x_pos, bar.get_y() + bar.get_height() / 2,
            f"r = {val:+.3f}", va="center", ha=ha, fontsize=9)
ax.set_xlim(-1.05, 1.05)
ax.xaxis.set_minor_locator(mticker.MultipleLocator(0.1))
ax.grid(axis="x", which="major", alpha=0.3)
fig.tight_layout()
save_fig(fig, "fig3_correlation_bar.png")


# -----------------------------------------------------------------------
# FIGURE 4: Parallel coordinates
# -----------------------------------------------------------------------
print("Figure 4: Parallel coordinates")

param_arrays = np.column_stack([df[k].values for k in PARAM_KEYS])
param_mins   = param_arrays.min(axis=0)
param_maxs   = param_arrays.max(axis=0)
param_norm   = (param_arrays - param_mins) / (param_maxs - param_mins + 1e-12)
x_positions  = np.arange(n_params)

fig, ax = plt.subplots(figsize=(max(10, 2.2 * n_params), 6))

for i in np.argsort(kge_vals):
    color    = KGE_CMAP(KGE_NORM(kge_vals[i]))
    norm_val = float(KGE_NORM(kge_vals[i]))
    alpha    = 0.30 + 0.50 * norm_val
    ax.plot(x_positions, param_norm[i], color=color, alpha=alpha,
            linewidth=1.2, zorder=int(norm_val * 100))

ax.plot(x_positions, param_norm[best_idx],
        color="red", linewidth=2.5, zorder=200,
        label=f"Best run  KGE={best_kge:.3f}")

for j, key in enumerate(PARAM_KEYS):
    ax.axvline(j, color="gray", linewidth=0.8, alpha=0.5)
    ax.text(j, -0.04, PARAM_META[key]["fmt"].format(param_mins[j]),
            ha="center", va="top", fontsize=7, color="gray",
            transform=ax.get_xaxis_transform())
    ax.text(j,  1.04, PARAM_META[key]["fmt"].format(param_maxs[j]),
            ha="center", va="bottom", fontsize=7, color="gray",
            transform=ax.get_xaxis_transform())

ax.set_xticks(x_positions)
ax.set_xticklabels(PARAM_LABELS, fontsize=8.5)
ax.set_yticks([0, 0.5, 1.0])
ax.set_yticklabels(["Min", "Mid", "Max"], fontsize=9)
ax.set_ylabel("Normalised parameter value", fontsize=10)
ax.set_title(
    f"Parallel coordinates -- {n_params}-param LHS  {SERIES_TITLE}  (n={len(df)})\n"
    f"Lines colored by KGE  |  {EVENT_LABEL}  |  {FIXED_NOTE}",
    fontsize=12
)
sm = plt.cm.ScalarMappable(cmap=KGE_CMAP, norm=KGE_NORM)
sm.set_array([])
fig.colorbar(sm, ax=ax, label="KGE", shrink=0.7, pad=0.02)
ax.legend(fontsize=9, loc="upper left", facecolor="white", framealpha=0.9)
fig.tight_layout()
save_fig(fig, "fig4_parallel_coordinates.png")


# -----------------------------------------------------------------------
# FIGURE 5: Pairwise scatter matrix -- C(n_params, 2) panels
# -----------------------------------------------------------------------
pairs  = list(combinations(range(n_params), 2))
n_cols = N_COLS_PAIRWISE
n_rows = (len(pairs) + n_cols - 1) // n_cols
print(f"Figure 5: Pairwise scatter matrix ({len(pairs)} panels)")

fig, axes = plt.subplots(n_rows, n_cols, figsize=(16, 4 * n_rows + 2))
axes_flat = np.atleast_1d(axes).flat

for ax_i, (pi, pj) in enumerate(pairs):
    ax = axes_flat[ax_i]
    ki, kj = PARAM_KEYS[pi], PARAM_KEYS[pj]
    ax.scatter(df[ki].values, df[kj].values,
               c=kge_vals, cmap=KGE_CMAP, norm=KGE_NORM,
               s=25, edgecolors="white", linewidths=0.3, alpha=0.85, zorder=3)
    ax.scatter(df[ki].iloc[best_idx], df[kj].iloc[best_idx],
               s=130, marker="*", color="white", edgecolors="black",
               linewidths=1.2, zorder=5, label=f"Best\nKGE={best_kge:.3f}")
    ax.set_xlabel(PARAM_META[ki]["label"], fontsize=7.5)
    ax.set_ylabel(PARAM_META[kj]["label"], fontsize=7.5)
    ax.legend(fontsize=6.5, loc="upper right", facecolor="white", framealpha=0.8)
    ax.tick_params(labelsize=7)
    ax.grid(alpha=0.25)

for ax_i in range(len(pairs), n_rows * n_cols):
    axes_flat[ax_i].set_visible(False)

sm = plt.cm.ScalarMappable(cmap=KGE_CMAP, norm=KGE_NORM)
sm.set_array([])
fig.colorbar(sm, ax=np.atleast_1d(axes).ravel().tolist(), label="KGE", shrink=0.5, pad=0.02)
fig.suptitle(
    f"Pairwise parameter scatter -- {n_params}-param LHS  {SERIES_TITLE}  (n={len(df)})\n"
    f"Colored by KGE  |  {EVENT_LABEL}  |  star = best run",
    fontsize=13, y=1.01
)
fig.tight_layout()
save_fig(fig, "fig5_pairwise_scatter.png")


# -----------------------------------------------------------------------
# FIGURE 6: KGE vs each parameter -- 1D response curves
# -----------------------------------------------------------------------
print("Figure 6: KGE vs each parameter (1D response)")

fig = plt.figure(figsize=(4 * min(n_params, 4) + 2, 9))
all_axes = build_response_curve_axes(fig, n_params)

for ax, key in zip(all_axes, PARAM_KEYS):
    xi = df[key].values
    ax.scatter(xi, kge_vals, c=kge_vals, cmap=KGE_CMAP, norm=KGE_NORM,
               s=25, edgecolors="white", linewidths=0.4, alpha=0.85, zorder=3)
    ax.scatter(df[key].iloc[best_idx], best_kge,
               s=150, marker="*", color="white", edgecolors="black",
               linewidths=1.2, zorder=5, label=f"Best KGE={best_kge:.3f}")
    sort_order = np.argsort(xi)
    xs_sorted  = xi[sort_order]
    ys_sorted  = kge_vals[sort_order]
    window     = max(5, len(df) // 8)
    ys_smooth  = pd.Series(ys_sorted).rolling(window, center=True, min_periods=1).median().values
    ax.plot(xs_sorted, ys_smooth, color="navy", linewidth=1.6,
            linestyle="--", alpha=0.7, label="Rolling median")
    ax.axhline(0, color="gray", linewidth=0.8, linestyle=":", alpha=0.6)
    ax.set_xlabel(PARAM_META[key]["label"], fontsize=8.5)
    ax.set_ylabel("KGE", fontsize=8.5)
    ax.legend(fontsize=7, loc="lower right", facecolor="white", framealpha=0.85)
    ax.grid(alpha=0.25)

fig.suptitle(
    f"KGE response to each parameter -- {n_params}-param LHS  {SERIES_TITLE}  (n={len(df)})\n"
    f"{EVENT_LABEL}  |  Dashed = rolling median  |  {FIXED_NOTE}",
    fontsize=12
)
save_fig(fig, "fig6_kge_vs_each_param.png")


# -----------------------------------------------------------------------
# FIGURE 7: PBIAS vs KGE scatter
# -----------------------------------------------------------------------
print("Figure 7: PBIAS vs KGE scatter")

fig, ax = plt.subplots(figsize=(9, 6))
sc = ax.scatter(pbias_vals, kge_vals, c=ks_vals, cmap="plasma",
                s=35, edgecolors="white", linewidths=0.4, alpha=0.85, zorder=3)
ax.scatter(pbias_vals[best_idx], kge_vals[best_idx],
           s=200, marker="*", color="white", edgecolors="black",
           linewidths=1.5, zorder=5, label=f"Best run  KGE={best_kge:.3f}")
ax.axvline(0, color="black", linewidth=0.9, linestyle="--", alpha=0.5,
           label="PBIAS = 0 (no volume bias)")
ax.axhline(0, color="gray", linewidth=0.8, linestyle=":", alpha=0.5,
           label="KGE = 0 (no skill)")
ax.set_xlabel("PBIAS (%)  -- positive = over-predict volume", fontsize=11)
ax.set_ylabel("KGE", fontsize=11)
ax.set_title(
    f"PBIAS vs KGE -- {n_params}-param LHS  {SERIES_TITLE}  (n={len(df)})\n"
    f"Points colored by Ks multiplier  |  {EVENT_LABEL}",
    fontsize=12
)
fig.colorbar(sc, ax=ax, label="Ks multiplier")
ax.legend(fontsize=9, loc="lower right", facecolor="white", framealpha=0.9)
ax.grid(alpha=0.25)
fig.tight_layout()
save_fig(fig, "fig7_pbias_vs_kge.png")


# -----------------------------------------------------------------------
# FIGURE 8: Top-15 runs as formatted table
# -----------------------------------------------------------------------
print("Figure 8: Top-15 table")

top_cols_display = {k: PARAM_META[k]["short"] for k in PARAM_KEYS}
top_cols_display.update({"kge": "KGE", "nse": "NSE", "pbias_pct": "PBIAS %",
                         "kge_r": "r (KGE)", "kge_alpha": "alpha", "kge_beta": "beta"})
fmt_map = {PARAM_META[k]["short"]: PARAM_META[k]["table_fmt"] for k in PARAM_KEYS}
fmt_map.update({"KGE": "{:.3f}", "NSE": "{:.3f}", "PBIAS %": "{:+.1f}",
                "r (KGE)": "{:.3f}", "alpha": "{:.3f}", "beta": "{:.3f}"})

top_cols_available = [c for c in top_cols_display if c in df.columns]
top15 = df.sort_values("kge", ascending=False).head(15)[top_cols_available].copy()
top15 = top15.rename(columns=top_cols_display)

for col, fmt in fmt_map.items():
    if col in top15.columns:
        top15[col] = top15[col].apply(lambda v: fmt.format(v))

fig, ax = plt.subplots(figsize=(2.2 * len(top15.columns), 5.5))
ax.axis("off")
tbl = ax.table(cellText=top15.values, colLabels=top15.columns,
               cellLoc="center", loc="center")
tbl.auto_set_font_size(False)
tbl.set_fontsize(7.5)
tbl.scale(1.0, 1.55)

for j in range(len(top15.columns)):
    tbl[0, j].set_facecolor("#2c3e50")
    tbl[0, j].set_text_props(color="white", fontweight="bold")
for i in range(1, len(top15) + 1):
    bg = "#eaf4ea" if i == 1 else ("#f7f7f7" if i % 2 == 0 else "white")
    for j in range(len(top15.columns)):
        tbl[i, j].set_facecolor(bg)

ax.set_title(
    f"Top 15 runs by KGE -- {n_params}-param LHS  {SERIES_TITLE}  (n={len(df)})\n"
    f"{EVENT_LABEL}  |  {FIXED_NOTE}  |  Green row = best run",
    fontsize=11, pad=12
)
fig.tight_layout()
save_fig(fig, "fig8_top15_table.png")


# -----------------------------------------------------------------------
# FIGURE 9: KGE component decomposition vs Ks
# -----------------------------------------------------------------------
print("Figure 9: KGE component decomposition vs Ks")

kge_r_vals     = df["kge_r"].values
kge_alpha_vals = df["kge_alpha"].values
kge_beta_vals  = df["kge_beta"].values

components = [
    {"col": kge_r_vals,     "label": "r  (timing correlation)",     "ideal": 1.0, "color": "#2a9d8f"},
    {"col": kge_alpha_vals, "label": "\u03b1  (variability ratio)", "ideal": 1.0, "color": "#e9c46a"},
    {"col": kge_beta_vals,  "label": "\u03b2  (bias ratio)",        "ideal": 1.0, "color": "#e76f51"},
]

fig, axes = plt.subplots(1, 3, figsize=(15, 5), sharey=False)
window = max(5, len(df) // 8)

for ax, comp in zip(axes, components):
    sc = ax.scatter(ks_vals, comp["col"], c=kge_vals, cmap=KGE_CMAP, norm=KGE_NORM,
                    s=35, edgecolors="white", linewidths=0.4, alpha=0.85, zorder=3)
    ax.scatter(ks_vals[best_idx], comp["col"][best_idx],
               s=180, marker="*", color="white", edgecolors="black",
               linewidths=1.2, zorder=5, label=f"Best KGE={best_kge:.3f}")
    sort_order = np.argsort(ks_vals)
    xs_sorted  = ks_vals[sort_order]
    ys_sorted  = comp["col"][sort_order]
    ys_smooth  = pd.Series(ys_sorted).rolling(window, center=True, min_periods=1).median().values
    ax.plot(xs_sorted, ys_smooth, color="navy", linewidth=1.6,
            linestyle="--", alpha=0.7, label="Rolling median")
    ax.axhline(comp["ideal"], color=comp["color"], linewidth=1.2,
               linestyle="-", alpha=0.6, label=f"Ideal = {comp['ideal']:.1f}")
    ax.set_xlabel("Ks multiplier", fontsize=10)
    ax.set_ylabel(comp["label"], fontsize=10)
    ax.set_title(comp["label"], fontsize=11)
    ax.legend(fontsize=8, loc="best", facecolor="white", framealpha=0.85)
    ax.grid(alpha=0.25)

sm = plt.cm.ScalarMappable(cmap=KGE_CMAP, norm=KGE_NORM)
sm.set_array([])
fig.colorbar(sm, ax=axes.tolist(), label="KGE", shrink=0.7, pad=0.02)
fig.suptitle(
    f"KGE component decomposition vs Ks -- {n_params}-param LHS  {SERIES_TITLE}  (n={len(df)})\n"
    f"{EVENT_LABEL}  |  Dashed = rolling median  |  Colored line = ideal value",
    fontsize=12
)
fig.tight_layout()
save_fig(fig, "fig9_kge_components_vs_ks.png")


# ======================================================================
# OPTIONAL DEEP-DIVE FIGURES (fig10, fig11, ... -- series-specific)
# ======================================================================
def plot_single_vs_ks_pbias_deepdive(col, label, baseline_note, fig_name, title_tag):
    """3-panel template: (a) KGE vs col, colored by Ks; (b) col vs Ks, colored
    by KGE; (c) PBIAS vs col, colored by KGE. Used for psiB_mult in series 82/83."""
    print(f"Deep-dive: {title_tag}")
    vals   = df[col].values
    window = max(5, len(df) // 8)

    fig, axes = plt.subplots(1, 3, figsize=(16, 5.5))

    ax = axes[0]
    sc_a = ax.scatter(vals, kge_vals, c=ks_vals, cmap="viridis",
                       s=35, edgecolors="white", linewidths=0.4, alpha=0.85, zorder=3)
    ax.scatter(vals[best_idx], kge_vals[best_idx],
               s=180, marker="*", color="white", edgecolors="black",
               linewidths=1.2, zorder=5, label=f"Best KGE={best_kge:.3f}")
    sort_order = np.argsort(vals)
    ys_sm = pd.Series(kge_vals[sort_order]).rolling(window, center=True, min_periods=1).median().values
    ax.plot(vals[sort_order], ys_sm, color="navy", linewidth=1.6, linestyle="--",
            alpha=0.7, label="Rolling median")
    ax.axhline(0, color="gray", linewidth=0.8, linestyle=":", alpha=0.6)
    ax.set_xlabel(label, fontsize=10)
    ax.set_ylabel("KGE", fontsize=10)
    ax.set_title(f"KGE vs {label}\n(colored by Ks mult)", fontsize=11)
    fig.colorbar(sc_a, ax=ax, label="Ks multiplier", shrink=0.85)
    ax.legend(fontsize=8, loc="lower right", facecolor="white", framealpha=0.85)
    ax.grid(alpha=0.25)

    ax = axes[1]
    sc_b = ax.scatter(ks_vals, vals, c=kge_vals, cmap=KGE_CMAP, norm=KGE_NORM,
                       s=35, edgecolors="white", linewidths=0.4, alpha=0.85, zorder=3)
    ax.scatter(ks_vals[best_idx], vals[best_idx],
               s=180, marker="*", color="white", edgecolors="black",
               linewidths=1.2, zorder=5, label=f"Best KGE={best_kge:.3f}")
    ax.set_xlabel("Ks multiplier", fontsize=10)
    ax.set_ylabel(label, fontsize=10)
    ax.set_title(f"Ks x {label} interaction\n(colored by KGE)", fontsize=11)
    fig.colorbar(sc_b, ax=ax, label="KGE", shrink=0.85)
    ax.legend(fontsize=8, loc="upper right", facecolor="white", framealpha=0.85)
    ax.grid(alpha=0.25)

    ax = axes[2]
    sc_c = ax.scatter(vals, pbias_vals, c=kge_vals, cmap=KGE_CMAP, norm=KGE_NORM,
                       s=35, edgecolors="white", linewidths=0.4, alpha=0.85, zorder=3)
    ax.scatter(vals[best_idx], pbias_vals[best_idx],
               s=180, marker="*", color="white", edgecolors="black",
               linewidths=1.2, zorder=5, label=f"Best KGE={best_kge:.3f}")
    ax.axhline(0, color="black", linewidth=0.9, linestyle="--", alpha=0.5, label="PBIAS = 0")
    sort_order = np.argsort(vals)
    ys_sm = pd.Series(pbias_vals[sort_order]).rolling(window, center=True, min_periods=1).median().values
    ax.plot(vals[sort_order], ys_sm, color="navy", linewidth=1.6, linestyle="--",
            alpha=0.7, label="Rolling median")
    ax.set_xlabel(label, fontsize=10)
    ax.set_ylabel("PBIAS (%)", fontsize=10)
    ax.set_title(f"PBIAS vs {label}\n(colored by KGE -- does it shift volume?)", fontsize=11)
    fig.colorbar(sc_c, ax=ax, label="KGE", shrink=0.85)
    ax.legend(fontsize=8, loc="upper right", facecolor="white", framealpha=0.85)
    ax.grid(alpha=0.25)

    fig.suptitle(
        f"{title_tag} -- {n_params}-param LHS  {SERIES_TITLE}  (n={len(df)})\n"
        f"{EVENT_LABEL}  |  {baseline_note}",
        fontsize=11
    )
    fig.tight_layout()
    save_fig(fig, fig_name)


def plot_two_param_interaction_deepdive(col1, label1, col2, label2, baseline_note, fig_name, title_tag):
    """3-panel template: (a) KGE vs col1, colored by Ks; (b) KGE vs col2,
    colored by Ks; (c) col1 x col2 interaction, colored by KGE. Used for the
    channelwidthcoeff/thetaS_mult pair in series 83."""
    print(f"Deep-dive: {title_tag}")
    vals1  = df[col1].values
    vals2  = df[col2].values
    window = max(5, len(df) // 8)

    fig, axes = plt.subplots(1, 3, figsize=(16, 5.5))

    for ax, vals, label in ((axes[0], vals1, label1), (axes[1], vals2, label2)):
        sc = ax.scatter(vals, kge_vals, c=ks_vals, cmap="viridis",
                         s=35, edgecolors="white", linewidths=0.4, alpha=0.85, zorder=3)
        ax.scatter(vals[best_idx], kge_vals[best_idx],
                   s=180, marker="*", color="white", edgecolors="black",
                   linewidths=1.2, zorder=5, label=f"Best KGE={best_kge:.3f}")
        sort_order = np.argsort(vals)
        ys_sm = pd.Series(kge_vals[sort_order]).rolling(window, center=True, min_periods=1).median().values
        ax.plot(vals[sort_order], ys_sm, color="navy", linewidth=1.6, linestyle="--",
                alpha=0.7, label="Rolling median")
        ax.axhline(0, color="gray", linewidth=0.8, linestyle=":", alpha=0.6)
        ax.set_xlabel(label, fontsize=10)
        ax.set_ylabel("KGE", fontsize=10)
        ax.set_title(f"KGE vs {label}\n(colored by Ks mult)", fontsize=11)
        fig.colorbar(sc, ax=ax, label="Ks multiplier", shrink=0.85)
        ax.legend(fontsize=8, loc="lower right", facecolor="white", framealpha=0.85)
        ax.grid(alpha=0.25)

    ax = axes[2]
    sc_c = ax.scatter(vals1, vals2, c=kge_vals, cmap=KGE_CMAP, norm=KGE_NORM,
                       s=35, edgecolors="white", linewidths=0.4, alpha=0.85, zorder=3)
    ax.scatter(vals1[best_idx], vals2[best_idx],
               s=180, marker="*", color="white", edgecolors="black",
               linewidths=1.2, zorder=5, label=f"Best KGE={best_kge:.3f}")
    ax.set_xlabel(label1, fontsize=10)
    ax.set_ylabel(label2, fontsize=10)
    ax.set_title(f"{label1} x {label2} interaction\n(colored by KGE)", fontsize=11)
    fig.colorbar(sc_c, ax=ax, label="KGE", shrink=0.85)
    ax.legend(fontsize=8, loc="upper right", facecolor="white", framealpha=0.85)
    ax.grid(alpha=0.25)

    fig.suptitle(
        f"{title_tag} -- {n_params}-param LHS  {SERIES_TITLE}  (n={len(df)})\n"
        f"{EVENT_LABEL}  |  {baseline_note}",
        fontsize=11
    )
    fig.tight_layout()
    save_fig(fig, fig_name)


for i, dd in enumerate(DEEP_DIVES, start=10):
    if dd["kind"] == "single_vs_ks_pbias":
        plot_single_vs_ks_pbias_deepdive(
            col=dd["col"], label=dd["label"], baseline_note=dd["baseline_note"],
            fig_name=dd.get("fig_name", f"fig{i}_deepdive.png"), title_tag=dd["title_tag"],
        )
    elif dd["kind"] == "two_param_interaction":
        plot_two_param_interaction_deepdive(
            col1=dd["col1"], label1=dd["label1"], col2=dd["col2"], label2=dd["label2"],
            baseline_note=dd["baseline_note"],
            fig_name=dd.get("fig_name", f"fig{i}_deepdive.png"), title_tag=dd["title_tag"],
        )
    else:
        raise ValueError(f"Unknown deep-dive kind: {dd['kind']!r}")


# -----------------------------------------------------------------------
# CONSOLE SUMMARY
# -----------------------------------------------------------------------
print(f"\n{'='*65}")
print(f"All figures saved to:\n  {plot_dir}")
print(f"\nParameter-KGE correlations (Pearson r):")
for key, label in zip(PARAM_KEYS, PARAM_LABELS):
    r_corr = np.corrcoef(df[key].values, kge_vals)[0, 1]
    print(f"  {label:<45s}  r = {r_corr:+.3f}")
print(f"\nTop 5 runs by KGE:")
top5_cols  = ["run_id"] + PARAM_KEYS + ["kge", "pbias_pct"]
top5_avail = [c for c in top5_cols if c in df.columns]
print(df.sort_values("kge", ascending=False).head(5)[top5_avail]
        .to_string(index=False, float_format="%.4f"))
print(f"{'='*65}\n")
