"""
score_notebook_run_against_truth.py
======================================
Scores an ALREADY-EXECUTED tRIBS run (produced by running Run_Model.ipynb's
Cell 8 interactively, inside its own Jupyter kernel) against the
100_narrow synthetic truth -- WITHOUT re-running tRIBS.

Context: Section 7 of the "Handoff: Series 100 Storm-Magnitude
Investigation + Truth-Point Validation Anomaly" found that the true
parameter point (Ks_mult=7.0x, f_RS_abs=0.012, cv=4.5, r=0.24, n=0.026)
does not reproduce PBIAS~0% when scored against its own truth
(validate_truth_point_100_storms.py: PBIAS=-6.92%, KGE=0.9211 for
100_narrow), even though every input-side explanation (SPOPINTRVL, soil
table, mesh/met/rasters, binary) and non-determinism (two back-to-back
reruns were bit-for-bit identical across all 241 timesteps -- see
compare_truthcheck_reruns.py) have been ruled out. The remaining
hypothesis is an execution-context difference: truth was almost certainly
generated by running Run_Model.ipynb interactively (a Jupyter kernel
process calling os.system() directly), while
validate_truth_point_100_storms.py runs the identical os.system() call
from inside a subprocess.Popen(..., start_new_session=True) child (a
detached session/process group) of a terminal-launched script.

This script tests that hypothesis directly. Run rebuild_100_narrow_config.py
first, then run Run_Model.ipynb's Cells 3-8 to execute tRIBS for the
100_narrow point through the notebook's own execution path. THEN run this
script to score that output -- it mirrors run_sensitivity_single.py's
run_and_score() exactly (same Project/Results loading, same
_find_synth_truth_file() truth detection, same metric formulas) but skips
the os.system() line entirely, since tRIBS has already been run by the
notebook.

Interpretation:
  - PBIAS ~ 0%, KGE ~ 1.0  -->  EXECUTION-CONTEXT HYPOTHESIS CONFIRMED.
    Something about running tRIBS through a detached subprocess (vs.
    directly in a Jupyter kernel) produces a real, reproducible numerical
    difference -- worth taking directly to Josh.
  - PBIAS ~ -6.9%, KGE ~ 0.92 (matching the wrapped-script result)  -->
    EXECUTION-CONTEXT HYPOTHESIS RULED OUT. Both routes produce the
    identical answer, and the true cause remains unidentified -- back to
    the Section 8 open-questions list, starting with closing the b987925
    git loose end.
  - Anything else  -->  ambiguous, worth a closer look before concluding.

Output:
    Saves calibration_work/03_comparisons/csv_exports/
        SMF_20140812_100_truthcheck_100_narrow_NOTEBOOK_compare_obs_sim.csv
    (a distinct filename -- does NOT overwrite the wrapped-script's
    original ..._compare_obs_sim.csv or the _RUN1.csv copy from the
    determinism check.)
    Prints metrics and a direct side-by-side comparison against the
    wrapped-script's previously recorded result.

Usage (run from smf_demo/, AFTER Run_Model.ipynb's Cells 3-8 have executed
for the 100_narrow point):
    python score_notebook_run_against_truth.py
"""

import json
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd

from pytRIBS.classes import Project, Results
from run_sensitivity_single import _find_synth_truth_file

# -----------------------------------------------------------------------
# Previously recorded wrapped-script result, for direct comparison
# (validate_truth_point_100_storms.py, 100_narrow -- confirmed
# deterministic across 3 independent runs; see compare_truthcheck_reruns.py)
# -----------------------------------------------------------------------
WRAPPED_SCRIPT_RESULT = {
    "pbias": -6.9178, "kge": 0.9211, "r": 0.9804, "alpha": 0.9676, "beta": 0.9308,
}

# -----------------------------------------------------------------------
# PATHS -- same convention as run_sensitivity_single.py
# -----------------------------------------------------------------------
script_dir   = Path.cwd()
project_root = script_dir.parent if script_dir.name == "smf_demo" else script_dir
calib_dir    = project_root / "calibration_work"
config_path  = calib_dir / "current_run_config.json"

if not config_path.exists():
    sys.exit(f"ERROR: {config_path} not found. Run rebuild_100_narrow_config.py first.")

with open(config_path) as f:
    run_config = json.load(f)

run_id         = run_config["run_id"]
input_file     = run_config["input_file"]
event_start    = run_config["event_start"]
event_end      = run_config["event_end"]
csv_export_dir = Path(run_config["csv_export_dir"])

if run_id != "SMF_20140812_100_truthcheck_100_narrow":
    print(f"WARNING: current_run_config.json points at '{run_id}', not the "
          f"100_narrow truthcheck run. Run rebuild_100_narrow_config.py "
          f"again before scoring, or this comparison will be meaningless.\n")

qout_path = Path(run_config["output_prefix"] + "_Outlet.qout")
if not qout_path.exists():
    sys.exit(f"ERROR: {qout_path} not found. Have you run Run_Model.ipynb's "
             f"Cells 3-8 for this config yet?")

# -----------------------------------------------------------------------
# Load simulated streamflow -- identical to run_and_score() / notebook
# Cells 10-11 (Project + Results, get_qout_results()). tRIBS is NOT
# re-run here; this just reads whatever the notebook already produced.
# -----------------------------------------------------------------------
name = run_config["location"]
proj = Project(os.getcwd(), name, 26912)

results = Results(input_file, meta=proj.meta)
results.get_mrf_results()
results.get_element_results()
strmflw_sim_raw = results.get_qout_results()

# -----------------------------------------------------------------------
# Load truth (or real gauge) -- identical detection logic to
# run_sensitivity_single.py, via the shared _find_synth_truth_file().
# -----------------------------------------------------------------------
truth_file_override = run_config.get("truth_file")
synth_file = _find_synth_truth_file(calib_dir, truth_file_override)

if synth_file is not None:
    print(f"  [SYNTH MODE] Reading observed from: {synth_file.name}")
    obs_raw = pd.read_csv(
        synth_file, sep=r'\s+', skiprows=1,
        names=['Time_hr', 'Qstrm_m3s', 'Hlev_m']
    )
    obs_raw['datetime'] = pd.to_datetime(
        obs_raw['Time_hr'] * 3600, unit='s', origin=pd.Timestamp('2014-08-01')
    )
    obs_raw.set_index('datetime', inplace=True)
    obs_raw['Observed_CMS'] = obs_raw['Qstrm_m3s']
    obs_df = obs_raw
else:
    print("  [GAUGE MODE] Reading observed from SMF_Observations xlsx")
    obs_filepath = '../smf_init_data/met/SMF_Observations_1993-2025.xlsx'
    obs_df = pd.read_excel(obs_filepath, sheet_name='Discharge', skiprows=6)
    obs_df['datetime'] = pd.to_datetime(
        obs_df['Date'].astype(str) + ' ' + obs_df['Time'].astype(str)
    )
    obs_df.set_index('datetime', inplace=True)
    obs_df['Observed_CMS'] = obs_df['cfs'] * 0.0283168

# -----------------------------------------------------------------------
# Align to 5-minute intervals -- identical to run_and_score()
# -----------------------------------------------------------------------
strmflw_sim = strmflw_sim_raw.copy()
strmflw_sim['Time'] = pd.to_datetime(strmflw_sim['Time'])
strmflw_sim.set_index('Time', inplace=True)

if synth_file is not None:
    obs_resampled = obs_df['Observed_CMS'].resample('5min').interpolate(method='time')
else:
    obs_resampled = obs_df['Observed_CMS'].resample('5min').mean()

sim_resampled = strmflw_sim['Qstrm_m3s'].resample('5min').mean()

compare_df = pd.DataFrame({
    'Observed':  obs_resampled,
    'Simulated': sim_resampled,
}).dropna()

event_df = compare_df.loc[event_start:event_end].copy()
if event_df.empty:
    sys.exit(f"ERROR: event_df is empty for {run_id}. Check event window and outputs.")

print(f"  Aligned event timesteps: {len(event_df)}")

# -----------------------------------------------------------------------
# Save comparison CSV -- DISTINCT filename; does not overwrite the
# wrapped-script's original result or the RUN1 determinism-check copy.
# -----------------------------------------------------------------------
csv_export_dir.mkdir(parents=True, exist_ok=True)
compare_csv = csv_export_dir / f"{run_id}_NOTEBOOK_compare_obs_sim.csv"
event_df.to_csv(compare_csv, index=True)
print(f"  Saved: {compare_csv.name}")

# -----------------------------------------------------------------------
# Metrics -- identical formulas to run_sensitivity_single.py
# -----------------------------------------------------------------------
obs = event_df['Observed']
sim = event_df['Simulated']

r     = np.corrcoef(sim, obs)[0, 1]
alpha = np.std(sim) / np.std(obs)
beta  = np.mean(sim) / np.mean(obs)
kge   = 1 - np.sqrt((r - 1) ** 2 + (alpha - 1) ** 2 + (beta - 1) ** 2)

# Kling et al. (2012) modified KGE, added alongside the 2009 formula
# per Handoff_KGE2012Transition_v1.md. gamma = alpha/beta exactly.
gamma    = alpha / beta
kge_2012 = 1 - np.sqrt((r - 1) ** 2 + (gamma - 1) ** 2 + (beta - 1) ** 2)

nse   = 1 - (np.sum((sim - obs) ** 2) / np.sum((obs - obs.mean()) ** 2))
pbias = 100 * (np.sum(sim - obs) / np.sum(obs))
rmse  = np.sqrt(np.mean((sim - obs) ** 2))

obs_peak, sim_peak   = obs.max(), sim.max()
obs_tpeak, sim_tpeak = obs.idxmax(), sim.idxmax()
peak_error_pct       = (sim_peak - obs_peak) / obs_peak * 100

print(f"\n=== NOTEBOOK-EXECUTION run at the true point, scored against 100_narrow truth ===")
print(f"  PBIAS         {pbias:+.4f} %")
print(f"  KGE           {kge:.4f}   (r={r:.4f}, alpha={alpha:.4f}, beta={beta:.4f})")
print(f"  KGE_2012      {kge_2012:.4f}   (r={r:.4f}, gamma={gamma:.4f}, beta={beta:.4f})")
print(f"  NSE           {nse:.4f}")
print(f"  RMSE          {rmse:.4f} m3/s")
print(f"  Peak error    {peak_error_pct:+.2f} %   "
      f"(obs peak {obs_peak:.2f} @ {obs_tpeak}, sim peak {sim_peak:.2f} @ {sim_tpeak})")

print(f"\n=== Direct comparison: notebook execution vs. wrapped-script execution ===")
print(f"  {'metric':10s} {'wrapped-script':>16s} {'notebook':>16s} {'delta':>10s}")
notebook_vals = {"pbias": pbias, "kge": kge, "r": r, "alpha": alpha, "beta": beta}
for key, label in [("pbias", "PBIAS %"), ("kge", "KGE"), ("r", "r"),
                    ("alpha", "alpha"), ("beta", "beta")]:
    wrapped_val = WRAPPED_SCRIPT_RESULT[key]
    nb_val      = notebook_vals[key]
    print(f"  {label:10s} {wrapped_val:16.4f} {nb_val:16.4f} {nb_val - wrapped_val:+10.4f}")

if abs(pbias) < 1.0 and kge > 0.98:
    print(f"\n  --> EXECUTION-CONTEXT HYPOTHESIS CONFIRMED: near-perfect self-reproduction")
    print(f"      when run through the notebook's own path. The subprocess/detached-")
    print(f"      session wrapper is implicated -- worth taking to Josh.")
elif abs(pbias - WRAPPED_SCRIPT_RESULT["pbias"]) < 0.5:
    print(f"\n  --> EXECUTION-CONTEXT HYPOTHESIS RULED OUT: matches the wrapped-script")
    print(f"      result closely. The true cause is still unidentified -- see Section 8")
    print(f"      open questions (close the b987925 git loose end next).")
else:
    print(f"\n  --> AMBIGUOUS: differs from both 0% and the wrapped-script result --")
    print(f"      worth a closer look before concluding either way.")
